version: "3"

services:
  dev_menu:
    image: centos:7.6.1810
    ports:
      - "9680:9679"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/www/dev/menu:/var/www/menu:rw
      - /var/log/dev/menu:/var/log/menu:rw
      - /var/log/dev/menu/config.ini:/config.ini:ro
        # env_file: env
    command: /var/www/menu/go_menu_run -config=config_dev.ini
    container_name: dev_menu 
