version: "3"

services:
  online_menu:
    image: centos:7.6.1810
    ports:
      - "9679:9679"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/www/online/menu:/var/www/menu:rw
      - /var/log/online/menu:/var/log/menu:rw
        # env_file: env
    command: /var/www/menu/go_menu_run -config=config_online.ini
    container_name: online_menu 
